/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp2;

import controller.ProjectController;
import controller.TaskController;
import java.util.Date;
import java.util.List;
import model.Project;
import model.Task;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        
        ProjectController projecon= new ProjectController();
        Project project=new Project();
        //inserir projeto
        /**project.setName("Projeto Teste");
        project.setDescription("Descricao teste");
        projecon.save(project);**/
        
        //atualizar projeto
        //project.setId(1);
        //project.setName("Projeto Inicial");
        //project.setDescription("Descricao do Projeto");
        //projecon.update(project);
        
       // List <Project> projeto= projecon.getAll();
       // System.out.println(projeto);
     // remover  projecon.removeById(1);
     
      Task task= new Task();
     TaskController taskcon= new TaskController();
     
     task.setId(1);
     task.setIdProject(2);
     task.setName("Telas da Inteface");
     task.setDescription("Devem ser criadas");
     task.setNotes("com notas");
     task.setCompleted(true);
     task.setDeadline(new Date());
     
    // taskcon.upadate(task);
   //  List <Task> tarefas= taskcon.getAll(2);
   //  System.out.println(tarefas);
   
  // taskcon.removeById(1);
    }
}