/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ProjectController;
import controller.TaskController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import model.Project;
import model.Task;
import util.ButtonColumnCellRederer;
import util.DeadlineColumnCellRederer;
import util.TaskTableModel;

/**
 *
 * @author WINDOWS
 */
public class MainScreen extends javax.swing.JFrame {

   ProjectController projectController;
   TaskController taskController;
   
   //é um modelo do componete visual
   DefaultListModel  projectModel; // responsavel pelo componete gráfico
   TaskTableModel taskModel;
   
    public MainScreen() {
        initComponents();
       
        initDataController();// iniciar os controller do bd
        initComponetsModel();
         decoreteTableTask();//decorar a tabela
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEmpatyList = new javax.swing.JPanel();
        jLabelEmpatyListIcon = new javax.swing.JLabel();
        jLabelEmpatyListTitle = new javax.swing.JLabel();
        jLabelEmpatyListSubTitle = new javax.swing.JLabel();
        PanelToolBar = new javax.swing.JPanel();
        LabelToolBarTitle = new javax.swing.JLabel();
        LabelToolBarSubTitle = new javax.swing.JLabel();
        PanelProjects = new javax.swing.JPanel();
        jLabelProjectsTitle = new javax.swing.JLabel();
        jLabelProjectsAdd = new javax.swing.JLabel();
        jPanelTasks = new javax.swing.JPanel();
        jLabelTasksTitle = new javax.swing.JLabel();
        jLabelTasksAdd = new javax.swing.JLabel();
        jPanelProjectList = new javax.swing.JPanel();
        ListProjects = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPanelTasks = new javax.swing.JScrollPane();
        jTableTasks = new javax.swing.JTable();

        jPanelEmpatyList.setBackground(new java.awt.Color(255, 255, 255));

        jLabelEmpatyListIcon.setForeground(new java.awt.Color(204, 204, 204));
        jLabelEmpatyListIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmpatyListIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lists.png"))); // NOI18N

        jLabelEmpatyListTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEmpatyListTitle.setForeground(new java.awt.Color(0, 153, 102));
        jLabelEmpatyListTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmpatyListTitle.setText("Nenhuma Tarefa por aqui :D");

        jLabelEmpatyListSubTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEmpatyListSubTitle.setForeground(new java.awt.Color(204, 204, 204));
        jLabelEmpatyListSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmpatyListSubTitle.setText("Clique no botão \"+\" para adicionar uma nova Tarefa");

        javax.swing.GroupLayout jPanelEmpatyListLayout = new javax.swing.GroupLayout(jPanelEmpatyList);
        jPanelEmpatyList.setLayout(jPanelEmpatyListLayout);
        jPanelEmpatyListLayout.setHorizontalGroup(
            jPanelEmpatyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelEmpatyListIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelEmpatyListLayout.createSequentialGroup()
                .addGroup(jPanelEmpatyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEmpatyListTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addComponent(jLabelEmpatyListSubTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelEmpatyListLayout.setVerticalGroup(
            jPanelEmpatyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpatyListLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabelEmpatyListIcon)
                .addGap(18, 18, 18)
                .addComponent(jLabelEmpatyListTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmpatyListSubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 700));

        PanelToolBar.setBackground(new java.awt.Color(0, 153, 102));

        LabelToolBarTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LabelToolBarTitle.setForeground(new java.awt.Color(255, 255, 255));
        LabelToolBarTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick.png"))); // NOI18N
        LabelToolBarTitle.setText("App Tarefas");

        LabelToolBarSubTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelToolBarSubTitle.setForeground(new java.awt.Color(255, 255, 255));
        LabelToolBarSubTitle.setText("Anote tudo, não esqueça nada!");

        javax.swing.GroupLayout PanelToolBarLayout = new javax.swing.GroupLayout(PanelToolBar);
        PanelToolBar.setLayout(PanelToolBarLayout);
        PanelToolBarLayout.setHorizontalGroup(
            PanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelToolBarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(LabelToolBarTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelToolBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelToolBarSubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        PanelToolBarLayout.setVerticalGroup(
            PanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelToolBarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(LabelToolBarTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelToolBarSubTitle)
                .addContainerGap())
        );

        LabelToolBarTitle.getAccessibleContext().setAccessibleName("    App Tarefas");

        PanelProjects.setBackground(new java.awt.Color(255, 255, 255));
        PanelProjects.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelProjectsTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelProjectsTitle.setForeground(new java.awt.Color(0, 153, 102));
        jLabelProjectsTitle.setText("Projetos");

        jLabelProjectsAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jLabelProjectsAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProjectsAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelProjectsLayout = new javax.swing.GroupLayout(PanelProjects);
        PanelProjects.setLayout(PanelProjectsLayout);
        PanelProjectsLayout.setHorizontalGroup(
            PanelProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProjectsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelProjectsAdd)
                .addGap(62, 62, 62))
        );
        PanelProjectsLayout.setVerticalGroup(
            PanelProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelProjectsAdd)
                    .addComponent(jLabelProjectsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelProjectsAdd.getAccessibleContext().setAccessibleName("");

        jPanelTasks.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTasks.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTasksTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTasksTitle.setForeground(new java.awt.Color(0, 153, 102));
        jLabelTasksTitle.setText("Tarefas");

        jLabelTasksAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jLabelTasksAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTasksAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTasksLayout = new javax.swing.GroupLayout(jPanelTasks);
        jPanelTasks.setLayout(jPanelTasksLayout);
        jPanelTasksLayout.setHorizontalGroup(
            jPanelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTasksLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelTasksTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTasksAdd)
                .addGap(22, 22, 22))
        );
        jPanelTasksLayout.setVerticalGroup(
            jPanelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTasksTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTasksAdd))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabelTasksAdd.getAccessibleContext().setAccessibleName("");

        jPanelProjectList.setBackground(new java.awt.Color(255, 255, 255));
        jPanelProjectList.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jList1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setFixedCellHeight(50);
        jList1.setSelectionBackground(new java.awt.Color(0, 153, 102));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        ListProjects.setViewportView(jList1);

        javax.swing.GroupLayout jPanelProjectListLayout = new javax.swing.GroupLayout(jPanelProjectList);
        jPanelProjectList.setLayout(jPanelProjectListLayout);
        jPanelProjectListLayout.setHorizontalGroup(
            jPanelProjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjectListLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ListProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanelProjectListLayout.setVerticalGroup(
            jPanelProjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjectListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new java.awt.BorderLayout());

        jTableTasks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome ", "Descrição", "Prazo", "Tarefa Concluída"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTasks.setGridColor(new java.awt.Color(255, 255, 255));
        jTableTasks.setRowHeight(40);
        jTableTasks.setSelectionBackground(new java.awt.Color(153, 255, 153));
        jTableTasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableTasks.setShowHorizontalLines(true);
        jTableTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTasksMouseClicked(evt);
            }
        });
        jScrollPanelTasks.setViewportView(jTableTasks);

        jPanel5.add(jScrollPanelTasks, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelProjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelProjectList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelProjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProjectList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelProjectsAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProjectsAddMouseClicked
        // TODO add your handling code here:
        // quando clicla na label mais
        
        ProjectDialogScreen projectDialogScreen= new ProjectDialogScreen(this, rootPaneCheckingEnabled);// cria uma nova janela
        projectDialogScreen.setVisible(true); //torna visiviel pro usuario
        projectDialogScreen.addWindowListener(new WindowAdapter(){
        
        public void windowClosed (WindowEvent e){
        loadProject(); //recarrega os projetos , é como atualizar as paginas
        }
        }); //esse trecho de código avisa quando vai fechar a pgina que foi instanciada
        
    }//GEN-LAST:event_jLabelProjectsAddMouseClicked

    private void jLabelTasksAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTasksAddMouseClicked
       
        TaskDialogScreen taskDialogScreen= new TaskDialogScreen (this, rootPaneCheckingEnabled);
      //  taskDialogScreen.setProject(2); //tem que setar qual projeto
      
      int projectIndex= jList1.getSelectedIndex();// pega o index que esta selecionado
      Project project= (Project)projectModel.get(projectIndex);
      
      taskDialogScreen.setProject(project);
      
        taskDialogScreen.setVisible(rootPaneCheckingEnabled);
        //quando a janela de cadastro for fechada
        taskDialogScreen.addWindowListener(new WindowAdapter(){
        
        public void windowClosed (WindowEvent e){
        
         int projectIndex= jList1.getSelectedIndex();// pega o index que esta selecionado
             Project project= (Project)projectModel.get(projectIndex);
             loadTasks(project.getId());
        }
        
        });
        
        
    }//GEN-LAST:event_jLabelTasksAddMouseClicked
//quando cliclar sobre a tabela
    private void jTableTasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTasksMouseClicked
        // TODO add your handling code here:
       int rowIndex= jTableTasks.rowAtPoint(evt.getPoint()); //pega a linha que aconteceu o click
// informa qual é a linha de acordo com a coordenada
        int columnIndex= jTableTasks.columnAtPoint(evt.getPoint());// pega qual coluna aconteceu o click
      
        Task task= taskModel.getTasks().get(rowIndex); //pega qual linha foi cliclada
        
        switch (columnIndex){
        
            case 3:
                
                taskController.upadate(task);
            break;
            
            case 5:
                
                taskController.removeById(task.getId());
                taskModel.getTasks().remove(task);
                
                int projectIndex=jList1.getSelectedIndex();//pega o projeto  que esta selecionado
                Project project= (Project)projectModel.get(projectIndex);
                loadTasks(project.getId());
             break;
        }

    }//GEN-LAST:event_jTableTasksMouseClicked
// quando cliclar no painel de prjetos
    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        
        int projectIndex= jList1.getSelectedIndex(); //retorna o indice do item clicado( projeto)
        
        Project project= (Project)projectModel.get(projectIndex);
        loadTasks(project.getId());
        
    }//GEN-LAST:event_jList1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelToolBarSubTitle;
    private javax.swing.JLabel LabelToolBarTitle;
    private javax.swing.JScrollPane ListProjects;
    private javax.swing.JPanel PanelProjects;
    private javax.swing.JPanel PanelToolBar;
    private javax.swing.JLabel jLabelEmpatyListIcon;
    private javax.swing.JLabel jLabelEmpatyListSubTitle;
    private javax.swing.JLabel jLabelEmpatyListTitle;
    private javax.swing.JLabel jLabelProjectsAdd;
    private javax.swing.JLabel jLabelProjectsTitle;
    private javax.swing.JLabel jLabelTasksAdd;
    private javax.swing.JLabel jLabelTasksTitle;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelEmpatyList;
    private javax.swing.JPanel jPanelProjectList;
    private javax.swing.JPanel jPanelTasks;
    private javax.swing.JScrollPane jScrollPanelTasks;
    private javax.swing.JTable jTableTasks;
    // End of variables declaration//GEN-END:variables

    public void decoreteTableTask(){
        //customizando o header table
    jTableTasks.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD,14));
    jTableTasks.getTableHeader().setBackground(new Color (0,153,102)); // cor do fundo
    jTableTasks.getTableHeader().setForeground(new Color(255,255,255));// cor da letra
    
     jTableTasks.getColumnModel().getColumn(2).setCellRenderer(new DeadlineColumnCellRederer());
     
     jTableTasks.getColumnModel().getColumn(4).setCellRenderer(new ButtonColumnCellRederer("edit"));
      jTableTasks.getColumnModel().getColumn(5).setCellRenderer(new ButtonColumnCellRederer("delete"));
    //criando um sort automtico para as colunas da table
   // jTableTasks.setAutoCreateRowSorter(true); //permite fazer a ordenação por colunas
    }
    
    public void initDataController(){
    
        projectController= new ProjectController(); // instancia o objeto ProjectController
        taskController= new TaskController();
    
    }
    
    public void initComponetsModel(){
    
    projectModel= new  DefaultListModel ();
    loadProject();//carregar os dados pra dentro do modelo
    
    taskModel= new TaskTableModel(); // instanciando o taskModel
    jTableTasks.setModel(taskModel);
    
     if (!projectModel.isEmpty()) {
     jList1.setSelectedIndex(0);
      int projectIndex = jList1.getSelectedIndex();
            Project project = (Project) projectModel.get(projectIndex);
            loadTasks(project.getId());
            // é executado quando o projeto é inicializado
     }
   
    }
    
   /* private void showJTableTasks (boolean hasTasks){
    
    if(hasTasks){
      //existem tarefas
        if(jPanelEmpatyList.isVisible()){
        //remove a tela de lista vazia se tiver tarefas
            jPanelEmpatyList.setVisible(false);
            jPanel5.remove(jPanelEmpatyList);
        }
        
        jPanelEmpatyList.add(jScrollPanelTasks);
        jScrollPanelTasks.setVisible(true);
        jScrollPanelTasks.setSize(jPanel5.getWidth(), jPanel5.getHeight());
    }else{
    
        if(jScrollPanelTasks.isVisible()){
        
        jScrollPanelTasks.setVisible(false);
        jPanel5.remove(jScrollPanelTasks);
        }
        
        jPanel5.add(jPanelEmpatyList);
        jPanelEmpatyList.setVisible(true);
        jPanelEmpatyList.setSize(jPanel5.getWidth(), jPanel5.getHeight());
    
    }
    }
 */
    
    private void showJTableTasks(boolean isEmptyTable) {
        if (isEmptyTable) {
            if (jPanelEmpatyList.isVisible()) {
                jPanelEmpatyList.setVisible(false);
                jPanel5.remove(jPanelEmpatyList);
            }

            jPanel5.add(jScrollPanelTasks);
            jScrollPanelTasks.setVisible(true);
            jScrollPanelTasks.setSize(jPanel5.getWidth(), jPanel5.getHeight());
        } else {
            if (jScrollPanelTasks.isVisible()) {
                jScrollPanelTasks.setVisible(false);
                jPanel5.remove(jScrollPanelTasks);
            }

            jPanel5.add(jPanelEmpatyList);
            jPanelEmpatyList.setVisible(true);
            jPanelEmpatyList.setSize(jPanel5.getWidth(), jPanel5.getHeight());
        }
    }

    
    public void loadTasks(int idProject){
    // metodo que carrega as tarefas do banco de dados
    
    List <Task> tasks= taskController.getAll(idProject);//carrega todas as tarefas que pertence ao um prjeto especifico
   
   taskModel.setTasks(tasks);
   showJTableTasks (!tasks.isEmpty());
     
    }
    
    
    public void loadProject(){
    
        List<Project> projects= projectController.getAll();
        projectModel.clear(); //caso tenha algo dado é limpado
       
        for(int i=0; i<projects.size(); i++){
        
              Project projeto= projects.get(i);
              projectModel.addElement(projeto);
        }
        
     jList1.setModel(projectModel);
    }
}
